services:
  db:
    ports:
      - "5432:5432"

  backend:
    volumes:
      - ./backend:/app:Z
    environment:
      FLASK_ENV: development
    command: python wsgi.py

  frontend:
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    command: npm run dev
