services:
  db:
    ports:
      - "5432:5432"

  backend:
    volumes:
      - ./backend:/app
    environment:
      FLASK_DEBUG: "1"
    command: python wsgi.py

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
